name: BOX

on:
  push:
    branches: [ "SmokeR24.1-stable-P" ]
  pull_request:
    branches: [ "SmokeR24.1-stable-P" ]

jobs:
  build:
    name: My first job
    runs-on: ubuntu-18.04
    steps:
    - name: Print Hello Word
      uses: A233S/SmokeR24.1-kernel@SmokeR24.1-stable-P
      env:
        MY_BOX: Hello Word
    - name: asa
      run: |
        echo $MY_BOX
        ls
        pwd
        echo 111 > 1.txt
