name: C/C++ CI

on:
  push:
    branches: [ "SmokeR24.1-stable-P" ]
  pull_request:
    branches: [ "SmokeR24.1-stable-P" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: hhhd
        uses: A233S/SmokeR24.1-kernel@SmokeR24.1-stable-P
        env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         BRANCH: echo 1
         FOLDER: echo 2
         BUILD_SCRIPT: echo 3
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
